name: Kasm Firefox

on:
  workflow_dispatch:

jobs:
  firefox:
    runs-on: ubuntu-latest

    services:
      kasm-firefox:
        image: kasmweb/firefox:1.17.0
        env:
          VNC_PW: github
        ports:
          - 6901:6901
        options: >-
          --shm-size=1g

    steps:
      - name: Check container
        run: |
          docker ps
          echo "Kasm Firefox started"
